# Generated by Django 5.1.6 on 2025-06-22 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naija_doc_bd', '0002_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='Naija_doc_bd.school'),
        ),
    ]
