# Generated by Django 5.1.6 on 2025-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naija_doc_bd', '0003_alter_nurse_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], default='SSS1', max_length=10),
            preserve_default=False,
        ),
    ]
