# Generated by Django 5.1.6 on 2025-06-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naija_doc_bd', '0004_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Naija_doc_bd.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Naija_doc_bd.school'),
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('days', models.PositiveIntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_records', to='Naija_doc_bd.case')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Naija_doc_bd.drug')),
            ],
        ),
    ]
