# Generated by Django 5.1.6 on 2025-07-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naija_doc_bd', '0005_alter_case_student_alter_student_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
