# Generated by Django 5.2.4 on 2025-08-01 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naija_doc_bd', '0006_case_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('dose_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medication_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Naija_doc_bd.medicationrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Naija_doc_bd.student')),
            ],
        ),
    ]
